<?php
$growboostly_case_studies = [
    [
        'id' => 'b2b-lead-generation-saas',
        'title' => 'B2B Lead Generation System for a SaaS Company',
        'category' => 'Lead Generation',
        'client' => 'B2B SaaS Company (Confidential)',
        'location' => 'India & Global',
        'date' => 'Jan 2025',
        'image' => 'assets/img/innerpages/lead-generation-case-study.png',
        'thumb' => 'assets/img/innerpages/case-study-details-thumb-img.jpg',
        'logo_light' => 'assets/img/home4/case-study-logo1.png',
        'logo_dark' => 'assets/img/home4/case-study-logo1-light.png',
        'metric1_label' => 'Qualified Leads',
        'metric1_value' => '320',
        'metric1_suffix' => '%',
        'metric2_label' => 'Cost Per Lead',
        'metric2_suffix' => '%',
        'metric2_value' => '45',
        'metric2_prefix' => '-',
        'overview' => 'A growing B2B SaaS company was spending on ads and content but struggling to attract decision-makers with real buying intent. GrowBoostly built a targeted lead generation system with ICP mapping, LinkedIn and Google campaigns, landing pages and CRM-ready lead flow.',
        'challenges' => [
            ['label' => 'Low-Quality Inquiries', 'text' => 'Most form fills came from students, job seekers and unqualified traffic — not founders, managers or department heads.'],
            ['label' => 'No Structured Funnel', 'text' => 'There was no clear offer, landing page or follow-up process, so marketing spend did not convert into sales conversations.'],
        ],
        'outcomes' => [
            'Qualified lead volume increased significantly within the first campaign cycle',
            'Cost per lead dropped while lead quality improved',
            'Sales team received CRM-ready leads with source and intent data',
            'Pipeline visibility improved for faster follow-up and closing',
        ],
        'takeaways' => [
            ['label' => 'ICP First', 'text' => 'B2B growth improves when campaigns, messaging and landing pages are built around a clearly defined ideal customer profile.'],
            ['label' => 'Track Beyond Clicks', 'text' => 'Lead quality matters more than raw traffic — CRM integration and lead scoring help sales focus on high-intent prospects.'],
        ],
        'note' => 'After implementing ICP-based targeting, offer-led landing pages and CRM tracking, the client reported a <span>320% increase</span> in qualified leads and a <span>45% reduction</span> in cost per lead within five months.',
        'sidebar_m1' => 'Qualified Leads',
        'sidebar_m1_val' => '320',
        'sidebar_m2' => 'CPL Reduction',
        'sidebar_m2_val' => '45',
        'sidebar_m2_suffix' => '%',
    ],
    [
        'id' => 'google-ads-real-estate',
        'title' => 'Google Ads Funnel for a Real Estate Developer',
        'category' => 'Performance Marketing',
        'client' => 'Real Estate Developer (Confidential)',
        'location' => 'Mumbai, India',
        'date' => 'Nov 2024',
        'image' => 'assets/img/innerpages/performance-marketing-case-study.png',
        'thumb' => 'assets/img/innerpages/case-study-details-thumb-img.jpg',
        'logo_light' => 'assets/img/home4/case-study-logo2.png',
        'logo_dark' => 'assets/img/home4/case-study-logo2-light.png',
        'metric1_label' => 'Conversion Rate',
        'metric1_value' => '186',
        'metric1_suffix' => '%',
        'metric2_label' => 'Monthly Leads',
        'metric2_value' => '3',
        'metric2_suffix' => 'x',
        'overview' => 'A real estate brand needed more site visits and qualified buyer enquiries from high-intent search traffic. GrowBoostly rebuilt their Google Ads structure, landing experience and lead capture flow to improve conversion quality.',
        'challenges' => [
            ['label' => 'High Ad Spend, Low Conversions', 'text' => 'Campaigns were driving clicks but not enough booked site visits or sales-qualified enquiries.'],
            ['label' => 'Weak Landing Experience', 'text' => 'Generic ad-to-page journeys failed to communicate project value, location benefits and urgency.'],
        ],
        'outcomes' => [
            'Landing page conversion rate improved with clearer project messaging',
            'Monthly qualified lead volume tripled from paid search',
            'Cost per enquiry became more predictable for the sales team',
            'Campaign structure allowed better budget control by project and location',
        ],
        'takeaways' => [
            ['label' => 'Match Intent to Offer', 'text' => 'Real estate campaigns perform better when ad groups, keywords and landing pages align with buyer stage and project type.'],
            ['label' => 'Optimize the Full Journey', 'text' => 'Conversion gains come from improving the page, form flow and follow-up — not from increasing budget alone.'],
        ],
        'note' => 'With restructured Google Ads, localized landing pages and WhatsApp-ready lead capture, the client achieved a <span>186% lift</span> in conversion rate and <span>3x more</span> monthly qualified leads.',
        'sidebar_m1' => 'Conversion Lift',
        'sidebar_m1_val' => '186',
        'sidebar_m2' => 'Lead Growth',
        'sidebar_m2_val' => '3',
        'sidebar_m2_suffix' => 'x',
    ],
    [
        'id' => 'ai-seo-d2c-brand',
        'title' => 'AI-Powered SEO Growth for a D2C Brand',
        'category' => 'SEO & Content',
        'client' => 'D2C eCommerce Brand (Confidential)',
        'location' => 'India',
        'date' => 'Sep 2024',
        'image' => 'assets/img/innerpages/seo-case-study.png',
        'thumb' => 'assets/img/innerpages/case-study-details-thumb-img.jpg',
        'logo_light' => 'assets/img/innerpages/case-study-logo1.png',
        'logo_dark' => 'assets/img/innerpages/case-study-logo1-light.png',
        'metric1_label' => 'Organic Traffic',
        'metric1_value' => '420',
        'metric1_suffix' => '%',
        'metric2_label' => 'Organic Revenue',
        'metric2_value' => '210',
        'metric2_suffix' => '%',
        'overview' => 'A D2C brand relied heavily on paid ads and wanted sustainable organic growth. GrowBoostly implemented AI-assisted keyword research, content clusters, technical SEO fixes and conversion-focused product page optimization.',
        'challenges' => [
            ['label' => 'Limited Organic Visibility', 'text' => 'The website had thin product content, weak internal linking and almost no ranking traction for high-intent search terms.'],
            ['label' => 'Rising Ad Dependency', 'text' => 'Customer acquisition costs were increasing because organic channels were underdeveloped.'],
        ],
        'outcomes' => [
            'Organic traffic grew consistently across category and product pages',
            'Non-brand keyword rankings improved for purchase-intent searches',
            'Organic revenue contribution increased alongside paid channels',
            'Content system created a scalable foundation for future SEO growth',
        ],
        'takeaways' => [
            ['label' => 'Content Clusters Work', 'text' => 'Grouping product, category and educational content around buyer intent helps D2C brands rank and convert faster.'],
            ['label' => 'SEO Should Support Sales', 'text' => 'Traffic alone is not enough — product pages must be structured to turn search visitors into buyers.'],
        ],
        'note' => 'Within six months, the brand saw a <span>420% increase</span> in organic traffic and a <span>210% rise</span> in organic revenue contribution from improved rankings and page optimization.',
        'sidebar_m1' => 'Organic Traffic',
        'sidebar_m1_val' => '420',
        'sidebar_m2' => 'Organic Revenue',
        'sidebar_m2_val' => '210',
    ],
    [
        'id' => 'brand-identity-coaching',
        'title' => 'Brand Identity Refresh for an Education Brand',
        'category' => 'Branding',
        'client' => 'Coaching & Training Institute (Confidential)',
        'location' => 'Delhi NCR, India',
        'date' => 'Aug 2024',
        'image' => 'assets/img/innerpages/branding-case-study.png',
        'thumb' => 'assets/img/innerpages/case-study-details-thumb-img.jpg',
        'logo_light' => 'assets/img/innerpages/case-study-logo2.png',
        'logo_dark' => 'assets/img/innerpages/case-study-logo2-light.png',
        'metric1_label' => 'Enrollment Inquiries',
        'metric1_value' => '165',
        'metric1_suffix' => '%',
        'metric2_label' => 'Social Engagement',
        'metric2_value' => '92',
        'metric2_suffix' => '%',
        'overview' => 'An education brand looked outdated across website, social media and ad creatives. GrowBoostly redesigned the logo system, brand colors, typography and social identity to create a more premium and trustworthy market presence.',
        'challenges' => [
            ['label' => 'Inconsistent Brand Look', 'text' => 'Different teams used mismatched logos, colors and creative styles across digital and offline touchpoints.'],
            ['label' => 'Low Trust on Digital Channels', 'text' => 'Prospective students did not perceive the institute as modern or premium compared to competitors.'],
        ],
        'outcomes' => [
            'Brand identity became consistent across website and social profiles',
            'Enrollment inquiry quality improved with clearer positioning',
            'Ad creatives and organic posts performed better with unified branding',
            'Internal teams gained practical brand usage guidance',
        ],
        'takeaways' => [
            ['label' => 'Brand Builds Trust', 'text' => 'For education and service businesses, visual consistency directly affects enrollment confidence and lead quality.'],
            ['label' => 'Design for Usage', 'text' => 'Logo systems must work on ads, reels, websites and WhatsApp — not only in presentation decks.'],
        ],
        'note' => 'After the rebrand launch, enrollment inquiries increased by <span>165%</span> and social engagement improved by <span>92%</span> within the first quarter.',
        'sidebar_m1' => 'Inquiry Growth',
        'sidebar_m1_val' => '165',
        'sidebar_m2' => 'Engagement',
        'sidebar_m2_val' => '92',
    ],
    [
        'id' => 'meta-ads-ecommerce',
        'title' => 'Meta Ads Scaling for an Online Store',
        'category' => 'Paid Social',
        'client' => 'eCommerce Store (Confidential)',
        'location' => 'India',
        'date' => 'Jun 2024',
        'image' => 'assets/img/innerpages/paid-social-case-study.png',
        'thumb' => 'assets/img/innerpages/case-study-details-thumb-img.jpg',
        'logo_light' => 'assets/img/innerpages/case-study-logo3.png',
        'logo_dark' => 'assets/img/innerpages/case-study-logo3-light.png',
        'metric1_label' => 'ROAS',
        'metric1_value' => '4.2',
        'metric1_suffix' => 'x',
        'metric2_label' => 'Revenue Growth',
        'metric2_value' => '280',
        'metric2_suffix' => '%',
        'overview' => 'An online store wanted to scale Facebook and Instagram ads without losing profitability. GrowBoostly rebuilt audience strategy, creative testing, catalog campaigns and retargeting flows.',
        'challenges' => [
            ['label' => 'Unstable ROAS', 'text' => 'Previous campaigns generated sales spikes but could not maintain profitable returns at higher spend levels.'],
            ['label' => 'Weak Retargeting', 'text' => 'Cart abandoners and past visitors were not being nurtured with structured remarketing sequences.'],
        ],
        'outcomes' => [
            'Profitable scaling became possible with clearer audience segmentation',
            'Creative testing improved click-through and purchase rates',
            'Retargeting recovered lost revenue from warm audiences',
            'Reporting helped the client understand channel-level profitability',
        ],
        'takeaways' => [
            ['label' => 'Scale What Is Proven', 'text' => 'eCommerce growth on Meta works best when prospecting and retargeting are optimized separately with clear ROAS targets.'],
            ['label' => 'Creative Drives Performance', 'text' => 'Regular ad creative refresh and offer testing are essential for sustained paid social results.'],
        ],
        'note' => 'The store reached a stable <span>4.2x ROAS</span> at scale and achieved <span>280% revenue growth</span> from paid social within four months.',
        'sidebar_m1' => 'ROAS',
        'sidebar_m1_val' => '4.2',
        'sidebar_m2_suffix' => 'x',
        'sidebar_m2' => 'Revenue Growth',
        'sidebar_m2_val' => '280',
    ],
    [
        'id' => 'crm-automation-bpo',
        'title' => 'CRM & Lead Automation for a BPO Services Company',
        'category' => 'Automation',
        'client' => 'BPO & Service Company (Confidential)',
        'location' => 'India',
        'date' => 'Apr 2024',
        'image' => 'assets/img/innerpages/automation-case-study.png',
        'thumb' => 'assets/img/innerpages/case-study-details-thumb-img.jpg',
        'logo_light' => 'assets/img/home4/case-study-logo1.png',
        'logo_dark' => 'assets/img/home4/case-study-logo1-light.png',
        'metric1_label' => 'Sales-Ready Leads',
        'metric1_value' => '240',
        'metric1_suffix' => '%',
        'metric2_label' => 'Follow-up Time',
        'metric2_value' => '60',
        'metric2_suffix' => '%',
        'metric2_prefix' => '-',
        'overview' => 'A BPO services company was losing leads due to slow follow-up and manual processes. GrowBoostly integrated CRM workflows, WhatsApp automation, email nurturing and lead assignment rules.',
        'challenges' => [
            ['label' => 'Leads Going Cold', 'text' => 'Enquiries from website and ads were stored in spreadsheets with delayed sales follow-up.'],
            ['label' => 'No Nurture System', 'text' => 'Prospects who did not convert immediately received no structured communication or re-engagement.'],
        ],
        'outcomes' => [
            'Lead response time improved with automated assignment and alerts',
            'Sales-ready lead volume increased through better qualification flow',
            'Email and WhatsApp sequences re-engaged warm prospects',
            'Management gained clearer visibility into pipeline stages',
        ],
        'takeaways' => [
            ['label' => 'Speed Wins Deals', 'text' => 'For service businesses, faster follow-up and structured nurturing directly improve close rates.'],
            ['label' => 'Automate Repetitive Work', 'text' => 'CRM automation helps sales teams focus on conversations instead of manual lead admin.'],
        ],
        'note' => 'After CRM and automation setup, the company saw a <span>240% increase</span> in sales-ready leads and a <span>60% reduction</span> in average follow-up time.',
        'sidebar_m1' => 'Sales-Ready Leads',
        'sidebar_m1_val' => '240',
        'sidebar_m2' => 'Faster Follow-up',
        'sidebar_m2_val' => '60',
        'sidebar_m2_suffix' => '%',
    ],
];

function gb_get_case_study($id) {
    global $growboostly_case_studies;
    foreach ($growboostly_case_studies as $index => $study) {
        if ($study['id'] === $id) {
            $study['_index'] = $index;
            return $study;
        }
    }
    return null;
}

function gb_case_metric_display($study, $metric = 1) {
    $prefix = $study["metric{$metric}_prefix"] ?? '';
    $value = $study["metric{$metric}_value"];
    $suffix = $study["metric{$metric}_suffix"];
    return htmlspecialchars($prefix . $value . $suffix, ENT_QUOTES, 'UTF-8');
}
