<?php
$growboostly_service_details = [
    [
        'id' => 'lead-generation',
        'title' => 'Lead Generation Campaigns',
        'category' => 'Lead Generation',
        'tags' => ['Audience Targeting', 'Campaign Setup', 'Lead Quality'],
        'image' => 'assets/img/innerpages/lead-generation-case-study.png',
        'full_page' => 'services/b2b-lead-generation',
        'ideal_for' => 'B2B & B2C brands needing qualified pipeline',
        'timeline' => '2–4 weeks to launch',
        'overview' => 'GrowBoostly builds end-to-end lead generation campaigns that attract the right audience, capture intent at the right moment, and deliver sales-ready leads — not just form fills. From ICP mapping and offer strategy to channel setup and CRM handoff, every step is designed for measurable ROI.',
        'features' => [
            'Ideal customer profile (ICP) research and audience segmentation',
            'Multi-channel campaign setup — Google, Meta, LinkedIn and more',
            'Offer-led landing pages with conversion-focused copy and design',
            'Lead scoring, qualification rules and CRM-ready data capture',
            'Weekly optimization based on lead quality, CPL and close rates',
            'Transparent reporting dashboards for marketing and sales teams',
        ],
        'process' => [
            ['label' => 'Discovery & ICP', 'text' => 'We map your buyer personas, pain points, objections and best-performing offers before any ad spend goes live.'],
            ['label' => 'Campaign Architecture', 'text' => 'Channel mix, ad structure, budgets and tracking are configured for clean attribution from click to CRM.'],
            ['label' => 'Launch & Optimize', 'text' => 'We monitor lead quality daily, refine targeting and creative, and scale what converts into revenue.'],
        ],
        'why_choose' => [
            'Pipeline-focused — we optimize for qualified leads, not vanity metrics',
            'CRM-integrated workflows so sales gets context with every lead',
            'Experience across SaaS, real estate, education, eCommerce and services',
            'Transparent reporting with clear CPL, conversion and ROI visibility',
        ],
        'sidebar_note' => 'Clients typically see improved lead quality within the first 30–45 days as targeting, offers and landing pages are refined.',
        'sidebar_m1' => 'Channels',
        'sidebar_m1_val' => '5',
        'sidebar_m1_suffix' => '+',
        'sidebar_m2' => 'Avg. CPL Drop',
        'sidebar_m2_val' => '35',
        'sidebar_m2_suffix' => '%',
    ],
    [
        'id' => 'landing-funnels',
        'title' => 'Landing Pages & Funnels',
        'category' => 'Conversion',
        'tags' => ['Landing Pages', 'Sales Funnels', 'CRO'],
        'image' => 'assets/img/innerpages/funnels-service.png',
        'full_page' => 'services/sales-funnel-development',
        'ideal_for' => 'Brands running paid campaigns or product launches',
        'timeline' => '1–3 weeks per funnel stage',
        'overview' => 'High-traffic campaigns fail when landing pages do not match ad intent. GrowBoostly designs and builds conversion-focused landing pages and full sales funnels — from awareness to purchase — so every click has a clear next step and every stage is measured.',
        'features' => [
            'Campaign-specific landing page design and development',
            'Multi-step sales funnel architecture (awareness → decision)',
            'Mobile-first UX with fast load times and Core Web Vitals focus',
            'A/B-ready layouts for headline, offer and CTA testing',
            'Form optimization, WhatsApp CTAs and payment/checkout flows',
            'Integration with analytics, pixels and CRM/automation tools',
        ],
        'process' => [
            ['label' => 'Funnel Mapping', 'text' => 'We define each stage — traffic source, offer, page goal and follow-up — before design begins.'],
            ['label' => 'Design & Build', 'text' => 'Pages are built for speed, clarity and conversion with messaging aligned to ad intent.'],
            ['label' => 'Test & Scale', 'text' => 'Heatmaps, form analytics and A/B tests identify what to improve before scaling ad spend.'],
        ],
        'why_choose' => [
            'Pages engineered for paid traffic — not generic brochure sites',
            'Copy, design and development handled in one growth-focused team',
            'Funnel logic tied to your CRM and nurture sequences',
            'Continuous CRO improvements based on real conversion data',
        ],
        'sidebar_note' => 'Well-structured funnels often deliver <span>2–3x higher</span> conversion rates compared to sending paid traffic to generic homepages.',
        'sidebar_m1' => 'Page Speed',
        'sidebar_m1_val' => '90',
        'sidebar_m1_suffix' => '+',
        'sidebar_m2' => 'CVR Lift',
        'sidebar_m2_val' => '2',
        'sidebar_m2_suffix' => 'x',
    ],
    [
        'id' => 'performance-ads',
        'title' => 'Performance Ads',
        'category' => 'Performance Marketing',
        'tags' => ['Google Ads', 'Meta Ads', 'ROI Tracking'],
        'image' => 'assets/img/innerpages/performance-marketing-case-study.png',
        'full_page' => 'services/google-ads',
        'ideal_for' => 'Businesses ready to scale paid acquisition profitably',
        'timeline' => '1–2 weeks setup, ongoing optimization',
        'overview' => 'GrowBoostly manages performance advertising across Google, Meta, LinkedIn and retargeting channels with a single focus: profitable growth. We structure campaigns for clean tracking, optimize for lead quality and cost efficiency, and report in terms your finance team understands.',
        'features' => [
            'Google Search, Display, Performance Max and YouTube campaigns',
            'Meta (Facebook & Instagram) lead gen and eCommerce campaigns',
            'LinkedIn Ads for B2B account-based and decision-maker targeting',
            'Retargeting and remarketing sequences for warm audiences',
            'Conversion tracking, GA4/GTM setup and offline conversion import',
            'Budget pacing, bid strategy and creative testing at scale',
        ],
        'process' => [
            ['label' => 'Account Audit', 'text' => 'We review structure, tracking, keywords/audiences and historical performance before rebuilding.'],
            ['label' => 'Structured Launch', 'text' => 'Campaigns are organized by intent, offer and funnel stage with proper UTM and pixel setup.'],
            ['label' => 'ROI Optimization', 'text' => 'Weekly bid, creative and audience refinements based on CPL, ROAS and lead quality feedback.'],
        ],
        'why_choose' => [
            'Full-funnel view — ads, landing pages and follow-up optimized together',
            'No black-box reporting; you see spend, leads and cost per outcome',
            'Experience managing ₹5L to ₹50L+ monthly ad budgets',
            'Channel-agnostic recommendations — we scale what works, cut what does not',
        ],
        'sidebar_note' => 'Structured account rebuilds and landing page alignment typically improve ROAS within the first 60 days.',
        'sidebar_m1' => 'Platforms',
        'sidebar_m1_val' => '4',
        'sidebar_m1_suffix' => '+',
        'sidebar_m2' => 'ROAS Gain',
        'sidebar_m2_val' => '40',
        'sidebar_m2_suffix' => '%',
    ],
    [
        'id' => 'automation',
        'title' => 'Automation & Follow-Up',
        'category' => 'Automation',
        'tags' => ['WhatsApp', 'Email', 'CRM Integration'],
        'image' => 'assets/img/innerpages/automation-service.png',
        'full_page' => 'services/crm-integration',
        'ideal_for' => 'Teams losing leads due to slow or manual follow-up',
        'timeline' => '2–3 weeks implementation',
        'overview' => 'Leads go cold fast. GrowBoostly connects your ads, forms and CRM with automated WhatsApp, email and task-based follow-up — so every enquiry gets a timely, personalized response and nothing falls through the cracks.',
        'features' => [
            'WhatsApp Business API automation and chatbot flows',
            'Email drip sequences triggered by form fills and behaviour',
            'CRM integration — HubSpot, Zoho, Salesforce, Pipedrive and more',
            'Instant lead alerts to sales reps via WhatsApp, SMS or Slack',
            'Lead routing rules by geography, product or deal size',
            'Automated reminders, no-show recovery and re-engagement campaigns',
        ],
        'process' => [
            ['label' => 'Workflow Design', 'text' => 'We map your sales process and define triggers, messages and escalation rules.'],
            ['label' => 'Integration Setup', 'text' => 'Forms, ads, CRM and messaging tools are connected with clean data sync.'],
            ['label' => 'Test & Refine', 'text' => 'Flows are tested end-to-end and tuned based on response rates and conversion data.'],
        ],
        'why_choose' => [
            'Speed-to-lead automation that improves close rates measurably',
            'Works with your existing CRM — no rip-and-replace required',
            'WhatsApp-first approach suited to Indian buyer behaviour',
            'Full visibility into follow-up status for sales managers',
        ],
        'sidebar_note' => 'Businesses implementing instant follow-up often see <span>3–5x higher</span> contact rates within the first month.',
        'sidebar_m1' => 'Response Time',
        'sidebar_m1_val' => '<5',
        'sidebar_m1_suffix' => 'min',
        'sidebar_m2' => 'Contact Rate',
        'sidebar_m2_val' => '3',
        'sidebar_m2_suffix' => 'x',
    ],
    [
        'id' => 'lead-nurturing',
        'title' => 'Lead Nurturing & Conversion',
        'category' => 'Lead Generation',
        'tags' => ['Qualification', 'Follow-Up', 'Conversion Tracking'],
        'image' => 'assets/img/innerpages/lead-nurturing-service.png',
        'full_page' => 'services/lead-nurturing',
        'ideal_for' => 'Brands with leads that need warming before purchase',
        'timeline' => '2–4 weeks strategy + setup',
        'overview' => 'Not every lead buys on day one. GrowBoostly designs nurture programmes that educate, build trust and move prospects through your funnel — with lead scoring, segmentation and conversion tracking so marketing and sales stay aligned on what is working.',
        'features' => [
            'Lead scoring models based on behaviour, source and profile fit',
            'Segmented email and WhatsApp nurture sequences by buyer stage',
            'Content-led warming — case studies, demos, offers and social proof',
            'Sales handoff triggers when leads hit qualification thresholds',
            'Conversion tracking from first touch to closed deal',
            'Re-engagement campaigns for dormant and lost opportunities',
        ],
        'process' => [
            ['label' => 'Funnel Analysis', 'text' => 'We identify where leads drop off and what content or touchpoints move them forward.'],
            ['label' => 'Sequence Build', 'text' => 'Multi-channel nurture flows are created with clear goals at each stage.'],
            ['label' => 'Measure & Improve', 'text' => 'Open rates, reply rates, SQL conversion and revenue attribution guide ongoing tweaks.'],
        ],
        'why_choose' => [
            'Nurture strategy tied to revenue — not just email open rates',
            'Sales and marketing alignment via shared lead scoring rules',
            'Content recommendations based on your industry and buyer journey',
            'Full-funnel attribution so you know which touches drive closes',
        ],
        'sidebar_note' => 'Structured nurturing typically increases SQL conversion by <span>25–50%</span> for mid-ticket B2B and service businesses.',
        'sidebar_m1' => 'Touchpoints',
        'sidebar_m1_val' => '8',
        'sidebar_m1_suffix' => '+',
        'sidebar_m2' => 'SQL Lift',
        'sidebar_m2_val' => '35',
        'sidebar_m2_suffix' => '%',
    ],
    [
        'id' => 'growth-strategy',
        'title' => 'Growth Strategy & Optimization',
        'category' => 'Strategy',
        'tags' => ['Analytics', 'A/B Testing', 'Scaling'],
        'image' => 'assets/img/innerpages/strategy-service.png',
        'full_page' => 'services/ab-testing',
        'ideal_for' => 'Teams ready to scale what works and cut waste',
        'timeline' => 'Ongoing monthly partnership',
        'overview' => 'Growth is not a one-time campaign — it is a system. GrowBoostly provides ongoing strategy, performance analysis, A/B testing and scaling plans so your marketing engine compounds over time instead of resetting every quarter.',
        'features' => [
            'Monthly growth audits across ads, pages, CRM and nurture flows',
            'Structured A/B testing on headlines, offers, pages and audiences',
            'Channel mix optimization and budget reallocation recommendations',
            'Competitive and market analysis for positioning opportunities',
            'Scaling playbooks for winning campaigns and geographies',
            'Executive-ready reporting with ROI, pipeline and forecast insights',
        ],
        'process' => [
            ['label' => 'Performance Review', 'text' => 'We analyze full-funnel data — spend, leads, SQLs, closes and LTV — to find bottlenecks.'],
            ['label' => 'Hypothesis & Test', 'text' => 'Priority experiments are designed, launched and measured with statistical rigour.'],
            ['label' => 'Scale Winners', 'text' => 'Proven improvements are rolled out and budgets shift to highest-ROI channels and offers.'],
        ],
        'why_choose' => [
            'Strategic partner mindset — not just campaign operators',
            'Data-driven decisions backed by your actual pipeline metrics',
            'Cross-channel view connecting ads, pages, nurture and sales outcomes',
            'Flexible engagement — advisory, hands-on or hybrid models',
        ],
        'sidebar_note' => 'Clients on ongoing optimization retain <span>20–40% lower CPA</span> year-over-year as systems compound.',
        'sidebar_m1' => 'Tests / Mo',
        'sidebar_m1_val' => '4',
        'sidebar_m1_suffix' => '+',
        'sidebar_m2' => 'CPA Reduction',
        'sidebar_m2_val' => '30',
        'sidebar_m2_suffix' => '%',
    ],
];

function gb_get_service_detail($id) {
    global $growboostly_service_details;
    foreach ($growboostly_service_details as $index => $service) {
        if ($service['id'] === $id) {
            $service['_index'] = $index;
            return $service;
        }
    }
    return null;
}
